#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

# The logic to stop your application should be put in this script.

kill -9 `lsof -t -i :8080`
kill -9 `lsof -t -i :80`
kill -9 `lsof -t -i :15001`
kill -9 `lsof -t -i :15002`

if [ -z "$(ps -ef | grep testrubyserver.rb | grep -v grep)" ]
then
    client_result "Application is already stopped"
else
    kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
fi
